from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional, Tuple

from .constants import TICKS_PER_SECOND
from .geometry import Vec2, seconds_to_ticks


@dataclass(frozen=True)
class UnitSpec:
    unit_id: str
    label: str
    kind: str
    movement_type: str
    target_mode: str
    hp: int
    damage: int
    speed_tiles_per_minute: float
    attack_range: float
    sight_range: float
    hit_speed_ticks: int
    deploy_ticks: int
    mass: float
    radius: float
    projectile_speed_tiles_per_minute: float = 0.0
    splash_radius: float = 0.0
    first_attack_ticks: Optional[int] = None
    load_time_ticks: Optional[int] = None
    periodic_spawns: Tuple["SpawnSpec", ...] = ()
    death_spawns: Tuple["SpawnSpec", ...] = ()
    death_damage: int = 0
    death_splash_radius: float = 0.0
    footprint_tiles: float = 0.0
    lifetime_ticks: Optional[int] = None
    mechanics: Tuple[str, ...] = ()


@dataclass(frozen=True)
class SpawnSpec:
    units: Tuple[UnitSpec, ...]
    formation: Tuple[Vec2, ...] = (Vec2(0.0, 0.0),)
    initial_delay_ticks: int = 0
    period_ticks: Optional[int] = None
    requires_enemy_in_range: bool = False
    trigger_range: Optional[float] = None


@dataclass(frozen=True)
class SpellSpec:
    spell_id: str
    damage: int
    crown_tower_damage: int
    radius: float
    projectile_speed_tiles_per_minute: float
    knockback_tiles: float = 0.0
    mechanics: Tuple[str, ...] = ()


@dataclass(frozen=True)
class CardSpec:
    card_id: str
    display_name: str
    source_name: str
    kind: str
    elixir: int
    secondary_color: str
    units: Tuple[UnitSpec, ...] = ()
    formation: Tuple[Vec2, ...] = (Vec2(0.0, 0.0),)
    spell: Optional[SpellSpec] = None
    source_note: str = "Current Level 11 Fandom/Deckshop stats plus RoyaleAPI/Fandom hidden-stat fields."


def _ticks(seconds: float) -> int:
    return seconds_to_ticks(seconds, TICKS_PER_SECOND)


SPAWNED_SKELETON = UnitSpec(
    unit_id="skeleton",
    label="Skel",
    kind="troop",
    movement_type="ground",
    target_mode="ground",
    hp=81,
    damage=81,
    speed_tiles_per_minute=90,
    attack_range=0.5,
    sight_range=5.5,
    hit_speed_ticks=_ticks(1.0),
    deploy_ticks=0,
    mass=1,
    radius=0.2,
    first_attack_ticks=_ticks(0.5),
    load_time_ticks=_ticks(0.5),
)


SPAWNED_SPEAR_GOBLIN = UnitSpec(
    unit_id="spear_goblin",
    label="Spear Gob",
    kind="troop",
    movement_type="ground",
    target_mode="all",
    hp=133,
    damage=81,
    speed_tiles_per_minute=120,
    attack_range=5.0,
    sight_range=5.5,
    hit_speed_ticks=_ticks(1.7),
    deploy_ticks=0,
    mass=1,
    radius=0.5,
    projectile_speed_tiles_per_minute=500,
    first_attack_ticks=_ticks(0.5),
    load_time_ticks=_ticks(1.2),
)


CARD_SPECS: Dict[str, CardSpec] = {
    "knight": CardSpec(
        card_id="knight",
        display_name="Knight",
        source_name="Knight",
        kind="troop",
        elixir=3,
        secondary_color="#8f9399",
        units=(
            UnitSpec(
                unit_id="knight",
                label="Knight",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=1766,
                damage=202,
                speed_tiles_per_minute=60,
                attack_range=1.2,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.2),
                deploy_ticks=_ticks(1.0),
                mass=6,
                radius=0.5,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(0.7),
            ),
        ),
    ),
    "archers": CardSpec(
        card_id="archers",
        display_name="Archers",
        source_name="Archers",
        kind="troop",
        elixir=3,
        secondary_color="#f2a5c8",
        units=(
            UnitSpec(
                unit_id="archer",
                label="Archer",
                kind="troop",
                movement_type="ground",
                target_mode="all",
                hp=304,
                damage=112,
                speed_tiles_per_minute=60,
                attack_range=5.0,
                sight_range=5.5,
                hit_speed_ticks=_ticks(0.9),
                deploy_ticks=_ticks(1.0),
                mass=3,
                radius=0.5,
                projectile_speed_tiles_per_minute=600,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(0.4),
            ),
        ),
        formation=(Vec2(-0.45, 0.0), Vec2(0.45, 0.0)),
    ),
    "minions": CardSpec(
        card_id="minions",
        display_name="Minions",
        source_name="Minions",
        kind="troop",
        elixir=3,
        secondary_color="#2d8bea",
        units=(
            UnitSpec(
                unit_id="minion",
                label="Minion",
                kind="troop",
                movement_type="air",
                target_mode="all",
                hp=230,
                damage=107,
                speed_tiles_per_minute=90,
                attack_range=2.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.2),
                deploy_ticks=_ticks(1.0),
                mass=2,
                radius=0.3,
                projectile_speed_tiles_per_minute=1000,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(0.7),
            ),
        ),
        formation=(Vec2(0.0, -0.4), Vec2(-0.6, 0.5), Vec2(0.6, 0.5)),
    ),
    "minion_horde": CardSpec(
        card_id="minion_horde",
        display_name="Minion Horde",
        source_name="Minion Horde",
        kind="troop",
        elixir=5,
        secondary_color="#247fcf",
        units=(
            UnitSpec(
                unit_id="minion",
                label="Minion",
                kind="troop",
                movement_type="air",
                target_mode="all",
                hp=230,
                damage=107,
                speed_tiles_per_minute=90,
                attack_range=2.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.0),
                deploy_ticks=_ticks(1.0),
                mass=2,
                radius=0.5,
                projectile_speed_tiles_per_minute=1000,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(0.7),
            ),
        ),
        formation=(
            Vec2(-0.8, -0.55),
            Vec2(0.0, -0.65),
            Vec2(0.8, -0.55),
            Vec2(-0.8, 0.45),
            Vec2(0.0, 0.55),
            Vec2(0.8, 0.45),
        ),
    ),
    "spear_goblins": CardSpec(
        card_id="spear_goblins",
        display_name="Spear Goblins",
        source_name="Spear Goblins",
        kind="troop",
        elixir=2,
        secondary_color="#4fb95f",
        units=(
            UnitSpec(
                unit_id="spear_goblin",
                label="Spear Gob",
                kind="troop",
                movement_type="ground",
                target_mode="all",
                hp=133,
                damage=81,
                speed_tiles_per_minute=120,
                attack_range=5.0,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.7),
                deploy_ticks=_ticks(1.0),
                mass=1,
                radius=0.5,
                projectile_speed_tiles_per_minute=500,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(1.2),
            ),
        ),
        formation=(Vec2(0.0, -0.35), Vec2(-0.55, 0.45), Vec2(0.55, 0.45)),
    ),
    "goblins": CardSpec(
        card_id="goblins",
        display_name="Goblins",
        source_name="Goblins",
        kind="troop",
        elixir=2,
        secondary_color="#2f9b57",
        units=(
            UnitSpec(
                unit_id="goblin",
                label="Goblin",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=202,
                damage=120,
                speed_tiles_per_minute=120,
                attack_range=0.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.1),
                deploy_ticks=_ticks(1.0),
                mass=2,
                radius=0.4,
                first_attack_ticks=_ticks(0.2),
                load_time_ticks=_ticks(0.9),
            ),
        ),
        formation=(
            Vec2(-0.6, -0.5),
            Vec2(0.6, -0.5),
            Vec2(-0.6, 0.5),
            Vec2(0.6, 0.6),
        ),
    ),
    "goblin_gang": CardSpec(
        card_id="goblin_gang",
        display_name="Goblin Gang",
        source_name="Goblin Gang",
        kind="troop",
        elixir=3,
        secondary_color="#2fa858",
        units=(
            UnitSpec(
                unit_id="goblin",
                label="Goblin",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=202,
                damage=120,
                speed_tiles_per_minute=120,
                attack_range=0.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.1),
                deploy_ticks=_ticks(1.0),
                mass=2,
                radius=0.5,
                first_attack_ticks=_ticks(0.2),
                load_time_ticks=_ticks(0.9),
            ),
            UnitSpec(
                unit_id="goblin",
                label="Goblin",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=202,
                damage=120,
                speed_tiles_per_minute=120,
                attack_range=0.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.1),
                deploy_ticks=_ticks(1.0),
                mass=2,
                radius=0.5,
                first_attack_ticks=_ticks(0.2),
                load_time_ticks=_ticks(0.9),
            ),
            UnitSpec(
                unit_id="goblin",
                label="Goblin",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=202,
                damage=120,
                speed_tiles_per_minute=120,
                attack_range=0.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.1),
                deploy_ticks=_ticks(1.0),
                mass=2,
                radius=0.5,
                first_attack_ticks=_ticks(0.2),
                load_time_ticks=_ticks(0.9),
            ),
            UnitSpec(
                unit_id="spear_goblin",
                label="Spear Gob",
                kind="troop",
                movement_type="ground",
                target_mode="all",
                hp=133,
                damage=81,
                speed_tiles_per_minute=120,
                attack_range=5.0,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.7),
                deploy_ticks=_ticks(1.0),
                mass=2,
                radius=0.5,
                projectile_speed_tiles_per_minute=500,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(1.2),
            ),
            UnitSpec(
                unit_id="spear_goblin",
                label="Spear Gob",
                kind="troop",
                movement_type="ground",
                target_mode="all",
                hp=133,
                damage=81,
                speed_tiles_per_minute=120,
                attack_range=5.0,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.7),
                deploy_ticks=_ticks(1.0),
                mass=2,
                radius=0.5,
                projectile_speed_tiles_per_minute=500,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(1.2),
            ),
            UnitSpec(
                unit_id="spear_goblin",
                label="Spear Gob",
                kind="troop",
                movement_type="ground",
                target_mode="all",
                hp=133,
                damage=81,
                speed_tiles_per_minute=120,
                attack_range=5.0,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.7),
                deploy_ticks=_ticks(1.0),
                mass=2,
                radius=0.5,
                projectile_speed_tiles_per_minute=500,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(1.2),
            ),
        ),
        formation=(
            Vec2(-0.7, -0.45),
            Vec2(0.0, -0.55),
            Vec2(0.7, -0.45),
            Vec2(-0.7, 0.55),
            Vec2(0.0, 0.65),
            Vec2(0.7, 0.55),
        ),
    ),
    "bomber": CardSpec(
        card_id="bomber",
        display_name="Bomber",
        source_name="Bomber",
        kind="troop",
        elixir=2,
        secondary_color="#6a5acd",
        units=(
            UnitSpec(
                unit_id="bomber",
                label="Bomber",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=304,
                damage=225,
                speed_tiles_per_minute=60,
                attack_range=4.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.8),
                deploy_ticks=_ticks(1.0),
                mass=4,
                radius=0.5,
                projectile_speed_tiles_per_minute=400,
                splash_radius=1.5,
                first_attack_ticks=_ticks(0.2),
                load_time_ticks=_ticks(1.6),
                mechanics=("area_damage",),
            ),
        ),
    ),
    "skeletons": CardSpec(
        card_id="skeletons",
        display_name="Skeletons",
        source_name="Skeletons",
        kind="troop",
        elixir=1,
        secondary_color="#d8d2bf",
        units=(
            UnitSpec(
                unit_id="skeleton",
                label="Skel",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=81,
                damage=81,
                speed_tiles_per_minute=90,
                attack_range=0.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.0),
                deploy_ticks=_ticks(1.0),
                mass=1,
                radius=0.2,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(0.5),
            ),
        ),
        formation=(Vec2(0.0, -0.35), Vec2(-0.55, 0.45), Vec2(0.55, 0.45)),
    ),
    "barbarians": CardSpec(
        card_id="barbarians",
        display_name="Barbarians",
        source_name="Barbarians",
        kind="troop",
        elixir=5,
        secondary_color="#e0b23f",
        units=(
            UnitSpec(
                unit_id="barbarian",
                label="Barb",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=670,
                damage=192,
                speed_tiles_per_minute=60,
                attack_range=0.7,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.4),
                deploy_ticks=_ticks(1.0),
                mass=4,
                radius=0.5,
                first_attack_ticks=_ticks(0.4),
                load_time_ticks=_ticks(1.0),
            ),
        ),
        formation=(
            Vec2(-0.8, -0.45),
            Vec2(0.0, -0.45),
            Vec2(0.8, -0.45),
            Vec2(-0.4, 0.45),
            Vec2(0.4, 0.45),
        ),
    ),
    "elite_barbarians": CardSpec(
        card_id="elite_barbarians",
        display_name="Elite Barbarians",
        source_name="Elite Barbarians",
        kind="troop",
        elixir=6,
        secondary_color="#d69b2d",
        units=(
            UnitSpec(
                unit_id="elite_barbarian",
                label="E-Barb",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=1341,
                damage=384,
                speed_tiles_per_minute=90,
                attack_range=0.8,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.4),
                deploy_ticks=_ticks(1.0),
                mass=4,
                radius=0.5,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(1.0),
            ),
        ),
        formation=(Vec2(-0.45, 0.0), Vec2(0.45, 0.0)),
    ),
    "fire_spirit": CardSpec(
        card_id="fire_spirit",
        display_name="Fire Spirit",
        source_name="Fire Spirit",
        kind="troop",
        elixir=1,
        secondary_color="#ff6b2c",
        units=(
            UnitSpec(
                unit_id="fire_spirit",
                label="Fire Sp",
                kind="troop",
                movement_type="ground",
                target_mode="all",
                hp=230,
                damage=207,
                speed_tiles_per_minute=120,
                attack_range=2.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.0),
                deploy_ticks=_ticks(1.0),
                mass=1,
                radius=0.4,
                projectile_speed_tiles_per_minute=400,
                splash_radius=1.7,
                first_attack_ticks=_ticks(0.2),
                load_time_ticks=_ticks(0.1),
                mechanics=("kamikaze", "area_damage"),
            ),
        ),
    ),
    "bats": CardSpec(
        card_id="bats",
        display_name="Bats",
        source_name="Bats",
        kind="troop",
        elixir=2,
        secondary_color="#5b4a8f",
        units=(
            UnitSpec(
                unit_id="bat",
                label="Bat",
                kind="troop",
                movement_type="air",
                target_mode="all",
                hp=81,
                damage=81,
                speed_tiles_per_minute=120,
                attack_range=1.2,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.3),
                deploy_ticks=_ticks(1.0),
                mass=1,
                radius=0.3,
                first_attack_ticks=_ticks(0.6),
                load_time_ticks=_ticks(0.7),
            ),
        ),
        formation=(
            Vec2(-0.951057, 0.309017),
            Vec2(0.0, 1.0),
            Vec2(0.951057, 0.309017),
            Vec2(-0.587785, -0.809017),
            Vec2(0.587785, -0.809017),
        ),
    ),
    "fireball": CardSpec(
        card_id="fireball",
        display_name="Fireball",
        source_name="Fireball",
        kind="spell",
        elixir=4,
        secondary_color="#f47a23",
        spell=SpellSpec(
            spell_id="fireball",
            damage=688,
            crown_tower_damage=172,
            radius=2.5,
            projectile_speed_tiles_per_minute=600,
            knockback_tiles=1.0,
            mechanics=("traveling_spell", "area_damage", "knockback"),
        ),
    ),
    "rocket": CardSpec(
        card_id="rocket",
        display_name="Rocket",
        source_name="Rocket",
        kind="spell",
        elixir=6,
        secondary_color="#b24a36",
        spell=SpellSpec(
            spell_id="rocket",
            damage=1484,
            crown_tower_damage=342,
            radius=2.0,
            projectile_speed_tiles_per_minute=350,
            knockback_tiles=1.8,
            mechanics=("traveling_spell", "area_damage", "knockback"),
        ),
    ),
    "cannon": CardSpec(
        card_id="cannon",
        display_name="Cannon",
        source_name="Cannon",
        kind="building",
        elixir=3,
        secondary_color="#4a4d50",
        units=(
            UnitSpec(
                unit_id="cannon",
                label="Cannon",
                kind="building",
                movement_type="building",
                target_mode="ground",
                hp=824,
                damage=212,
                speed_tiles_per_minute=0,
                attack_range=5.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.0),
                deploy_ticks=_ticks(1.0),
                mass=0,
                radius=0.6,
                projectile_speed_tiles_per_minute=1000,
                first_attack_ticks=_ticks(1.0),
                load_time_ticks=0,
                footprint_tiles=2.4,
                lifetime_ticks=_ticks(30.0),
                mechanics=("lifetime",),
            ),
        ),
    ),
    "bomb_tower": CardSpec(
        card_id="bomb_tower",
        display_name="Bomb Tower",
        source_name="Bomb Tower",
        kind="building",
        elixir=4,
        secondary_color="#5e5961",
        units=(
            UnitSpec(
                unit_id="bomb_tower",
                label="Bomb Twr",
                kind="building",
                movement_type="building",
                target_mode="ground",
                hp=1356,
                damage=222,
                speed_tiles_per_minute=0,
                attack_range=6.0,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.6),
                deploy_ticks=_ticks(1.0),
                mass=0,
                radius=0.6,
                projectile_speed_tiles_per_minute=400,
                splash_radius=1.5,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(1.1),
                death_damage=222,
                death_splash_radius=3.0,
                footprint_tiles=2.4,
                lifetime_ticks=_ticks(30.0),
                mechanics=("lifetime", "area_damage", "death_bomb"),
            ),
        ),
    ),
    "wizard": CardSpec(
        card_id="wizard",
        display_name="Wizard",
        source_name="Wizard",
        kind="troop",
        elixir=5,
        secondary_color="#d94d34",
        units=(
            UnitSpec(
                unit_id="wizard",
                label="Wizard",
                kind="troop",
                movement_type="ground",
                target_mode="all",
                hp=755,
                damage=281,
                speed_tiles_per_minute=60,
                attack_range=5.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.4),
                deploy_ticks=_ticks(1.0),
                mass=5,
                radius=0.5,
                projectile_speed_tiles_per_minute=600,
                splash_radius=1.5,
                first_attack_ticks=_ticks(0.4),
                load_time_ticks=_ticks(1.0),
            ),
        ),
    ),
    "valkyrie": CardSpec(
        card_id="valkyrie",
        display_name="Valkyrie",
        source_name="Valkyrie",
        kind="troop",
        elixir=4,
        secondary_color="#c65d47",
        units=(
            UnitSpec(
                unit_id="valkyrie",
                label="Valk",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=1907,
                damage=266,
                speed_tiles_per_minute=60,
                attack_range=1.2,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.5),
                deploy_ticks=_ticks(1.0),
                mass=5,
                radius=0.5,
                splash_radius=1.9,
                first_attack_ticks=_ticks(0.1),
                load_time_ticks=_ticks(1.4),
                mechanics=("area_damage",),
            ),
        ),
    ),
    "mega_minion": CardSpec(
        card_id="mega_minion",
        display_name="Mega Minion",
        source_name="Mega Minion",
        kind="troop",
        elixir=3,
        secondary_color="#607d9f",
        units=(
            UnitSpec(
                unit_id="mega_minion",
                label="Mega Min",
                kind="troop",
                movement_type="air",
                target_mode="all",
                hp=837,
                damage=312,
                speed_tiles_per_minute=60,
                attack_range=1.6,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.6),
                deploy_ticks=_ticks(1.0),
                mass=6,
                radius=0.6,
                projectile_speed_tiles_per_minute=1000,
                first_attack_ticks=_ticks(0.4),
                load_time_ticks=_ticks(1.2),
            ),
        ),
    ),
    "giant": CardSpec(
        card_id="giant",
        display_name="Giant",
        source_name="Giant",
        kind="troop",
        elixir=5,
        secondary_color="#8a5b35",
        units=(
            UnitSpec(
                unit_id="giant",
                label="Giant",
                kind="troop",
                movement_type="ground",
                target_mode="buildings",
                hp=4090,
                damage=253,
                speed_tiles_per_minute=45,
                attack_range=1.2,
                sight_range=7.5,
                hit_speed_ticks=_ticks(1.5),
                deploy_ticks=_ticks(1.0),
                mass=18,
                radius=0.9,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(1.0),
            ),
        ),
    ),
    "royal_giant": CardSpec(
        card_id="royal_giant",
        display_name="Royal Giant",
        source_name="Royal Giant",
        kind="troop",
        elixir=6,
        secondary_color="#c9a44a",
        units=(
            UnitSpec(
                unit_id="royal_giant",
                label="RG",
                kind="troop",
                movement_type="ground",
                target_mode="buildings",
                hp=3164,
                damage=307,
                speed_tiles_per_minute=45,
                attack_range=5.0,
                sight_range=7.5,
                hit_speed_ticks=_ticks(1.7),
                deploy_ticks=_ticks(1.0),
                mass=18,
                radius=0.75,
                projectile_speed_tiles_per_minute=1000,
                first_attack_ticks=_ticks(0.7),
                load_time_ticks=_ticks(1.0),
            ),
        ),
    ),
    "hog_rider": CardSpec(
        card_id="hog_rider",
        display_name="Hog Rider",
        source_name="Hog Rider",
        kind="troop",
        elixir=4,
        secondary_color="#9c5b31",
        units=(
            UnitSpec(
                unit_id="hog_rider",
                label="Hog",
                kind="troop",
                movement_type="ground",
                target_mode="buildings",
                hp=1697,
                damage=317,
                speed_tiles_per_minute=120,
                attack_range=0.8,
                sight_range=9.5,
                hit_speed_ticks=_ticks(1.6),
                deploy_ticks=_ticks(1.0),
                mass=4,
                radius=0.6,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(1.1),
                mechanics=("river_jump",),
            ),
        ),
    ),
    "musketeer": CardSpec(
        card_id="musketeer",
        display_name="Musketeer",
        source_name="Musketeer",
        kind="troop",
        elixir=4,
        secondary_color="#8a50cc",
        units=(
            UnitSpec(
                unit_id="musketeer",
                label="Musk",
                kind="troop",
                movement_type="ground",
                target_mode="all",
                hp=721,
                damage=217,
                speed_tiles_per_minute=60,
                attack_range=6.0,
                sight_range=6.0,
                hit_speed_ticks=_ticks(1.0),
                deploy_ticks=_ticks(1.0),
                mass=5,
                radius=0.5,
                projectile_speed_tiles_per_minute=1000,
                first_attack_ticks=_ticks(0.7),
                load_time_ticks=_ticks(0.3),
            ),
        ),
    ),
    "dart_goblin": CardSpec(
        card_id="dart_goblin",
        display_name="Dart Goblin",
        source_name="Dart Goblin",
        kind="troop",
        elixir=3,
        secondary_color="#60b956",
        units=(
            UnitSpec(
                unit_id="dart_goblin",
                label="Dart Gob",
                kind="troop",
                movement_type="ground",
                target_mode="all",
                hp=261,
                damage=151,
                speed_tiles_per_minute=120,
                attack_range=6.5,
                sight_range=7.5,
                hit_speed_ticks=_ticks(0.8),
                deploy_ticks=_ticks(1.0),
                mass=3,
                radius=0.5,
                projectile_speed_tiles_per_minute=800,
                first_attack_ticks=_ticks(0.35),
                load_time_ticks=_ticks(0.35),
            ),
        ),
    ),
    "mini_pekka": CardSpec(
        card_id="mini_pekka",
        display_name="Mini P.E.K.K.A.",
        source_name="Mini P.E.K.K.A",
        kind="troop",
        elixir=4,
        secondary_color="#404348",
        units=(
            UnitSpec(
                unit_id="mini_pekka",
                label="Mini P",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=1390,
                damage=755,
                speed_tiles_per_minute=90,
                attack_range=0.8,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.6),
                deploy_ticks=_ticks(1.0),
                mass=4,
                radius=0.45,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(1.1),
            ),
        ),
    ),
    "pekka": CardSpec(
        card_id="pekka",
        display_name="P.E.K.K.A",
        source_name="P.E.K.K.A",
        kind="troop",
        elixir=7,
        secondary_color="#30343b",
        units=(
            UnitSpec(
                unit_id="pekka",
                label="P.E.K.K.A",
                kind="troop",
                movement_type="ground",
                target_mode="ground",
                hp=3760,
                damage=816,
                speed_tiles_per_minute=45,
                attack_range=1.2,
                sight_range=5.0,
                hit_speed_ticks=_ticks(1.8),
                deploy_ticks=_ticks(1.0),
                mass=18,
                radius=0.75,
                first_attack_ticks=_ticks(0.5),
                load_time_ticks=_ticks(1.3),
            ),
        ),
    ),
    "witch": CardSpec(
        card_id="witch",
        display_name="Witch",
        source_name="Witch",
        kind="troop",
        elixir=5,
        secondary_color="#6b45b8",
        units=(
            UnitSpec(
                unit_id="witch",
                label="Witch",
                kind="troop",
                movement_type="ground",
                target_mode="all",
                hp=839,
                damage=135,
                speed_tiles_per_minute=60,
                attack_range=5.5,
                sight_range=5.5,
                hit_speed_ticks=_ticks(1.1),
                deploy_ticks=_ticks(1.0),
                mass=8,
                radius=0.5,
                projectile_speed_tiles_per_minute=600,
                splash_radius=1.0,
                first_attack_ticks=_ticks(0.7),
                load_time_ticks=_ticks(0.4),
                periodic_spawns=(
                    SpawnSpec(
                        units=(SPAWNED_SKELETON,),
                        formation=(
                            Vec2(-1.0, 0.0),
                            Vec2(0.0, -1.0),
                            Vec2(-0.1, 1.0),
                            Vec2(1.0, 0.0),
                        ),
                        initial_delay_ticks=_ticks(1.0),
                        period_ticks=_ticks(7.0),
                    ),
                ),
                mechanics=("area_damage", "summons_skeletons"),
            ),
        ),
    ),
    "goblin_hut": CardSpec(
        card_id="goblin_hut",
        display_name="Goblin Hut",
        source_name="Goblin Hut",
        kind="building",
        elixir=5,
        secondary_color="#7a9f45",
        units=(
            UnitSpec(
                unit_id="goblin_hut",
                label="Gob Hut",
                kind="building",
                movement_type="building",
                target_mode="none",
                hp=1180,
                damage=0,
                speed_tiles_per_minute=0,
                attack_range=0.0,
                sight_range=0.0,
                hit_speed_ticks=0,
                deploy_ticks=_ticks(1.0),
                mass=0,
                radius=1.0,
                periodic_spawns=(
                    SpawnSpec(
                        units=(SPAWNED_SPEAR_GOBLIN,),
                        formation=(Vec2(-0.5, 0.0),),
                        initial_delay_ticks=_ticks(4.5),
                        period_ticks=_ticks(4.5),
                        requires_enemy_in_range=True,
                        trigger_range=6.0,
                    ),
                ),
                death_spawns=(
                    SpawnSpec(
                        units=(SPAWNED_SPEAR_GOBLIN,),
                        formation=(Vec2(-0.55, -0.45), Vec2(0.55, -0.45), Vec2(0.0, 0.45)),
                        requires_enemy_in_range=True,
                        trigger_range=6.0,
                    ),
                ),
                footprint_tiles=2.0,
                lifetime_ticks=_ticks(50.0),
                mechanics=("lifetime", "spawner_spear_goblins", "death_spawn_spear_goblins"),
            ),
        ),
    ),
    "tombstone": CardSpec(
        card_id="tombstone",
        display_name="Tombstone",
        source_name="Tombstone",
        kind="building",
        elixir=3,
        secondary_color="#6f7782",
        units=(
            UnitSpec(
                unit_id="tombstone",
                label="Tomb",
                kind="building",
                movement_type="building",
                target_mode="none",
                hp=529,
                damage=0,
                speed_tiles_per_minute=0,
                attack_range=0.0,
                sight_range=0.0,
                hit_speed_ticks=0,
                deploy_ticks=_ticks(1.0),
                mass=0,
                radius=1.0,
                periodic_spawns=(
                    SpawnSpec(
                        units=(SPAWNED_SKELETON,),
                        formation=(Vec2(-0.5, -0.35), Vec2(-0.5, 0.35)),
                        initial_delay_ticks=_ticks(3.1),
                        period_ticks=_ticks(3.1),
                    ),
                ),
                death_spawns=(
                    SpawnSpec(
                        units=(SPAWNED_SKELETON,),
                        formation=(Vec2(-0.5, 0.0), Vec2(0.2, -0.6), Vec2(0.2, 0.6)),
                    ),
                ),
                footprint_tiles=2.0,
                lifetime_ticks=_ticks(40.0),
                mechanics=("lifetime", "spawner_skeletons", "death_spawn_skeletons"),
            ),
        ),
    ),
}

# DEFAULT_DECK = (
#     "knight",
#     "musketeer",
#     "minions",
#     "giant",
#     "cannon",
#     "fireball",
#     "archers",
#     "mini_pekka",
# )
DEFAULT_DECK = (
    "hog_rider",
    "elite_barbarians",
    "royal_giant",
    "minion_horde",
    "goblin_gang",
    "witch",
    "goblins",
    "bats",
)

TOWER_SPECS: Dict[str, UnitSpec] = {
    "king": UnitSpec(
        unit_id="king_tower",
        label="King",
        kind="tower",
        movement_type="building",
        target_mode="all",
        hp=4824,
        damage=109,
        speed_tiles_per_minute=0,
        attack_range=8.5,
        sight_range=8.5,
        hit_speed_ticks=_ticks(1.0),
        deploy_ticks=0,
        mass=0,
        radius=1.7,
        projectile_speed_tiles_per_minute=1000,
    ),
    "princess": UnitSpec(
        unit_id="princess_tower",
        label="Tower",
        kind="tower",
        movement_type="building",
        target_mode="all",
        hp=3052,
        damage=109,
        speed_tiles_per_minute=0,
        attack_range=7.5,
        sight_range=7.5,
        hit_speed_ticks=_ticks(0.8),
        deploy_ticks=0,
        mass=0,
        radius=1.3,
        projectile_speed_tiles_per_minute=600,
        first_attack_ticks=_ticks(0.0),
        load_time_ticks=_ticks(0.8),
    ),
}
