ENGINE_VERSION = "cr-sim-prototype-0.1.0"

TICKS_PER_SECOND = 30
ARENA_ROWS = 32
ARENA_COLS = 18

SIDE_BLUE = "blue"
SIDE_RED = "red"
SIDES = (SIDE_BLUE, SIDE_RED)

ELIXIR_MILLI = 1000
START_ELIXIR_MILLI = 5000
MAX_ELIXIR_MILLI = 10000

# Legacy Retro Royale engine: normal elixir is 1.0 every 84 ticks at 30 FPS.
NORMAL_ELIXIR_TICKS = 84

# Converts card movement stats into simulator movement. Card stats remain source values.
TROOP_MOVEMENT_SPEED_FACTOR = 1.2

SUDDEN_DEATH_START_SECONDS = 180
MATCH_END_SECONDS = 300
SUDDEN_DEATH_START_TICKS = SUDDEN_DEATH_START_SECONDS * TICKS_PER_SECOND
MATCH_END_TICKS = MATCH_END_SECONDS * TICKS_PER_SECOND

KING_ACTIVATION_DELAY_SECONDS = 4.0
KING_ACTIVATION_DELAY_TICKS = int(KING_ACTIVATION_DELAY_SECONDS * TICKS_PER_SECOND)
